### ISSUE TITLE
Data Model Design

### ISSUE THREAD

**Issue by SaiMadhukar-1407** [ou-cs5213-sp24/capstone-management-system#12]
• Translation of the application’s requirements into a comprehensive data model.
• Identification of entities such as Users, Projects, Teams, Submissions, and Evaluations, and their respective
attributes and relationships.

**Comment by ferialna** [comment]
Excellent work on initiating the data model. To align with our project's milestone M4, let's ensure we address the following:

Clarify entity relationships and their implications for database scalability.
Ensure that the model adheres to security protocols as per our SQAP.
Update the issue with a progress timeline to keep track as per our project plan.

**Comment by Anu-2001** [comment]
We have designed the database and created the models according to the design.
