### ISSUE TITLE
Relationship Mapping

### ISSUE THREAD

**Issue by SaiMadhukar-1407** [ou-cs5213-sp24/capstone-management-system#14]
• Definition of relationships between models using ORM relationships such as ForeignKey,
ManyToManyField, and OneToOneField.
• Ensuring referential integrity and the efficient retrieval of related data through Django’s query syntax.
Database Migration Generation

**Comment by ferialna** [comment]
Great job defining the ORM relationships! Have we checked that the use of ForeignKey, ManyToManyField, and OneToOneField ensures referential integrity and supports efficient data retrieval?

**Comment by SaiMadhukar-1407** [comment]
I have defined all the relationships including foreignkey and all cardinal constraints.
