### ISSUE TITLE
Database Schema Creation

### ISSUE THREAD

**Issue by SaiMadhukar-1407** [ou-cs5213-sp24/capstone-management-system#16]
• Application of migrations to the development database using Django’s migrate command to create the
necessary database tables and relationships.
• Verification of the resulting database schema to ensure it accurately represents the data models.

**Comment by ferialna** [comment]
Great progress with applying migrations and setting up the development database.

**Comment by Shriya020** [comment]
We have setup the database and created all the necessary tables and relationships.
