### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by SaiMadhukar-1407** [ou-cs5213-sp24/capstone-management-system#18]
• Migration scripts generated, applied, and verified, resulting in an updated database schema ready for use
by the application.

**Comment by ferialna** [comment]
Great to hear that the migration scripts have been successfully generated and applied. It's important to ensure that the updated schema is fully aligned with our current development needs and the ORM objects definitions as outlined in M4

**Comment by nvn-jajapur** [comment]
I have contacted Group A's Jackson(Thanks to him) for database setup and created the database and a user for editing the database.
I have also gave permission to all my group members to edit the database.
