### ISSUE TITLE
Cloud Service Provider Selection 

### ISSUE THREAD

**Issue by Jayendra-varma** [ou-cs5213-sp24/capstone-management-system#19]
Task:
Evaluation and selection of a cloud service provider based on the system requirements, cost, scalability, and reliability. Providers considered include AWS, GCP, and Azure.

Definition of done:
Selection of a cloud service provider

**Comment by mounica908** [comment]
I appreciate your insights on this issue. Can you consider exploring the potential option for hosting with OU, alongside evaluating the cloud hosting options? Your efforts in examining both possibilities concurrently would be highly valuable. Thank you!

**Comment by Jayendra-varma** [comment]
OU IT server space has been considered for hosting the Capstone Management System by reviewing all the constraints.
