### ISSUE TITLE
Server Setup and configuration

### ISSUE THREAD

**Issue by Jayendra-varma** [ou-cs5213-sp24/capstone-management-system#20]
Description:
- Provisioning of cloud server instances (virtual machines) to host the web application and associated services. 
- Configuration of server specifications to match the expected load and performance requirements. 
- Manual installation of the operating system and necessary packages including web server software (e.g., Nginx, Apache), a database server (e.g., PostgreSQL, MySQL), and other dependencies. 
- Configuration of the network settings, including firewalls and security groups, to secure the server from unauthorized access. 

Definition of done : 
A fully configured and operational server ready to host the Capstone Management System in a production capacity.

**Comment by mounica908** [comment]
The issue appears to be well-defined, and it would be greatly appreciated if the tasks could be broken down into smaller issues, with one team member assigned to each. Thank you for your cooperation!

**Comment by Jayendra-varma** [comment]
OU IT server space has been created .
linux based os and other required services have been installed and are ready to use.
