### ISSUE TITLE
Application Deployment

### ISSUE THREAD

**Issue by Jayendra-varma** [ou-cs5213-sp24/capstone-management-system#21]
Description:
• Deployment of the Capstone Management System codebase to the server. 
• Setup of the web server to serve the application and manage traffic. 

Definition of done:
The latest stable version of the application deployed to the production server and accessible via a secure connection.

**Comment by mounica908** [comment]
A great issue with good "definition of done".

**Comment by Jayendra-varma** [comment]
since there is no initial version of the application that can be deployed i am closing this issue.
