### ISSUE TITLE
Database Configuration

### ISSUE THREAD

**Issue by Jayendra-varma** [ou-cs5213-sp24/capstone-management-system#22]
Description:
• Installation and configuration of the production database system. 
• Implementation of security measures such as strong passwords, encrypted connections, and restricted access to the database.

**Comment by mounica908** [comment]
To ensure a manageable workload, it would be advisable to incorporate the implementation of the security measures into Issue #23 . This approach would help distribute the tasks more effectively among the team.

Requires a "definition of done" to clarify completion criteria.

**Comment by Jayendra-varma** [comment]
postgres database has been installed and configured
necessary steps are given in the server access document submitted by Group A and the same has been uploaded in the branch M2
