### ISSUE TITLE
Security Measures

### ISSUE THREAD

**Issue by Jayendra-varma** [ou-cs5213-sp24/capstone-management-system#23]
Description:
• Implementation of security best practices, including SSL/TLS encryption for secure HTTP connections. 
• Regular updates and security patches applied to the server and software to protect against known vulnerabilities.

**Comment by mounica908** [comment]
The issue appears to be well defined. Requires a "definition of done" to clarify completion criteria.

**Comment by rajatpodder22** [comment]
Server environment is setup with OU firewall so incoming traffic can happen only within OU network. Secure ports are open for the server
