### ISSUE TITLE
Configure deployment workflow for test environment

### ISSUE THREAD

**Issue by UdayBhumireddy** [ou-cs5213-sp24/capstone-management-system#8]
Description: Create a deployment job in GitHub Actions to automatically deploy the CMS to the test environment upon successful merging into the main branch.
Tasks:
Define deployment steps and environment variables.
Manage credentials securely using GitHub secrets.
Ensure proper handling of configuration settings.

Definition of Done: The deployment job in GitHub Actions is set up to automatically deploy the CMS to the test environment after successful merging into the main branch, with deployment steps defined, environment variables managed securely using GitHub secrets, and proper handling of configuration settings ensured.

**Comment by UdayBhumireddy** [comment]
We are successfully able to integrate github to jenkins. If a file is merged into main branch it will be able to deploy in jenkins and in nginx. It is not automated due to permission issues

**Comment by mounica908** [comment]
You can ask for the permission in our channel and one of the project managers will be able to provide the permissions.
